export const ATTENDENCE_FETCH_ATTEMPTED_SUCCESSED =
  "ATTENDENCE_FETCH_ATTEMPTED_SUCCESSED";
export const ATTENDENCE_FETCH_ATTEMPTED_FAILED =
  "ATTENDENCE_FETCH_ATTEMPTED_FAILED";
export const ATTENDENCE_FETCH_ATTEMPTED = "ATTENDENCE_FETCH_ATTEMPTED";
