export const DASHBOARD_DATA_FETCH_ATTEMPTED_SUCCESSED =
  "DASHBOARD_DATA_FETCH_ATTEMPTED_SUCCESSED";
export const DASHBOARD_DATA_FETCH_ATTEMPTED_FAILED =
  "DASHBOARD_DATA_FETCH_ATTEMPTED_FAILED";
export const DASHBOARD_DATA_FETCH_ATTEMPTED = "DASHBOARD_DATA_FETCH_ATTEMPTED";
