export const DATE_SHEET_FETCH_ATTEMPTED_SUCCESSED =
  "DATE_SHEET_FETCH_ATTEMPTED_SUCCESSED";
export const DATE_SHEET_FETCH_ATTEMPTED_FAILED =
  "DATE_SHEET_FETCH_ATTEMPTED_FAILED";
export const DATE_SHEET_FETCH_ATTEMPTED = "DATE_SHEET_FETCH_ATTEMPTED";
