export const EVENTS_FETCH_ATTEMPTED_SUCCESSED =
  "EVENTS_FETCH_ATTEMPTED_SUCCESSED";
export const EVENTS_FETCH_ATTEMPTED_FAILED = "EVENTS_FETCH_ATTEMPTED_FAILED";
export const EVENTS_FETCH_ATTEMPTED = "EVENTS_FETCH_ATTEMPTED";
