export const LESSONS_FETCH_ATTEMPTED_SUCCESSED =
  "LESSONS_FETCH_ATTEMPTED_SUCCESSED";
export const LESSONS_FETCH_ATTEMPTED_FAILED = "LESSONS_FETCH_ATTEMPTED_FAILED";
export const LESSONS_FETCH_ATTEMPTED = "LESSONS_FETCH_ATTEMPTED";
