export const ONLINE_CLASSES_FETCH_ATTEMPTED_SUCCESSED =
  "ONLINE_CLASSES_FETCH_ATTEMPTED_SUCCESSED";
export const ONLINE_CLASSES_FETCH_ATTEMPTED_FAILED =
  "ONLINE_CLASSES_FETCH_ATTEMPTED_FAILED";
export const ONLINE_CLASSES_FETCH_ATTEMPTED = "ONLINE_CLASSES_FETCH_ATTEMPTED";
