export const SUBJECTS_FETCH_ATTEMPTED_SUCCESSED =
  "SUBJECTS_FETCH_ATTEMPTED_SUCCESSED";
export const SUBJECTS_FETCH_ATTEMPTED_FAILED =
  "SUBJECTS_FETCH_ATTEMPTED_FAILED";
export const SUBJECTS_FETCH_ATTEMPTED = "SUBJECTS_FETCH_ATTEMPTED";
