export const TIME_TABLE_FETCH_ATTEMPTED_SUCCESSED =
  "TIME_TABLE_FETCH_ATTEMPTED_SUCCESSED";
export const TIME_TABLE_FETCH_ATTEMPTED_FAILED =
  "TIME_TABLE_FETCH_ATTEMPTED_FAILED";
export const TIME_TABLE_FETCH_ATTEMPTED = "TIME_TABLE_FETCH_ATTEMPTED";
