export const TIMING_FETCH_ATTEMPTED_SUCCESSED =
  "TIMING_FETCH_ATTEMPTED_SUCCESSED";
export const TIMING_FETCH_ATTEMPTED_FAILED = "TIMING_FETCH_ATTEMPTED_FAILED";
export const TIMING_FETCH_ATTEMPTED = "TIMING_FETCH_ATTEMPTED";
