const userRouter = require('./user-router')
const timingRouter = require('./timing-router')
const onlineClassRouter = require('./online-class-router')
const courseRouter = require('./course-router')
const timeTableRouter = require('./time-table-router')
const resultsRouter = require('./results-router')
const lessonsRouter = require('./lessons-router')
const feeRouter = require('./fee-router')
const eventsRouter = require('./events-router')
const attendenceRouter = require('./attendence-router')
const dateSheetRouter = require('./date-sheet-router')
const leaveApplicationRouter = require('./leave-application-router')
const dashboardRouter = require('./dashboard-router')

module.exports = app => {
  app.use('/api', userRouter)
  app.use('/api', timingRouter)
  app.use('/api', onlineClassRouter)
  app.use('/api', courseRouter)
  app.use('/api', timeTableRouter)
  app.use('/api', resultsRouter)
  app.use('/api', lessonsRouter)
  app.use('/api', feeRouter)
  app.use('/api', eventsRouter)
  app.use('/api', attendenceRouter)
  app.use('/api', dateSheetRouter)
  app.use('/api', leaveApplicationRouter)
  app.use('/api', dashboardRouter)
}
